<?php

/**
 * Default system settings.
 *
 * Changes to these config files are not supported by BookStack and may break upon updates.
 * Configuration should be altered via the `.env` file or environment variables.
 * Do not edit this file unless you're happy to maintain any changes yourself.
 */

return [

    'app-name'             => 'BookStack',
    'app-logo'             => '',
    'app-name-header'      => true,
    'app-editor'           => 'wysiwyg',
    'app-color'            => '#1d75b6',
    'app-color-light'      => 'rgba(29,117,182,0.15)',
    'app-custom-head'      => false,
    'registration-enabled' => false,

];