#!/usr/bin/env php
<?php

if (php_sapi_name() !== 'cli') {
    exit;
}

require __DIR__ . '/vendor/autoload.php';

use Cli\Commands\BackupCommand;
use Cli\Commands\InitCommand;
use Minicli\App;

// Get the directory of the CLI "entrypoint", adjusted to be the real
// location where running via a phar.
$scriptDir = __DIR__;
if (str_starts_with($scriptDir, 'phar://')) {
    $scriptDir = dirname(Phar::running(false));
}
$bsDir = dirname($scriptDir);

// Load in our .env file from the parent directory
$dotenv = Dotenv\Dotenv::createImmutable($bsDir);
$dotenv->safeLoad();

// Setup our CLI
$app = new App();
$app->setSignature('./run');

$app->registerCommand('backup', [new BackupCommand($bsDir), 'handle']);
$app->registerCommand('init', [new InitCommand(), 'handle']);

try {
    $app->runCommand($argv);
} catch (Exception $error) {
    fwrite(STDERR, "An error occurred when attempting to run a command:\n");
    fwrite(STDERR, $error->getMessage() . "\n");
    exit(1);
}
