#!/usr/bin/env php
<?php

if (php_sapi_name() !== 'cli') {
    exit;
}

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Cli\Commands\BackupCommand;
use Cli\Commands\InitCommand;

// Get the directory of the CLI "entrypoint", adjusted to be the real
// location where running via a phar.
$scriptDir = __DIR__;
if (str_starts_with($scriptDir, 'phar://')) {
    $scriptDir = dirname(Phar::running(false));
}
$bsDir = dirname($scriptDir);

// Setup our CLI
$app = new Application('bookstack-system');

$app->add(new BackupCommand($bsDir));
$app->add(new InitCommand());

try {
    $app->run();
} catch (Exception $error) {
    fwrite(STDERR, "An error occurred when attempting to run a command:\n");
    fwrite(STDERR, $error->getMessage() . "\n");
    exit(1);
}
