ServerName localhost

# BookStack Apache configuration
<VirtualHost *:80>
    ServerName localhost
    DocumentRoot /app/public
    
    <Directory "/app/public">
        AllowOverride All
        Require all granted
    </Directory>
    
    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
