name: Deploy BookStack to Demo EC2

on:
  push:
    branches:
      - implement-custom-notification-for-slack-app

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Execute Deployment via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script_stop: true
          script: |
            cd ~/bookstack-demo
            
            # Sync code
            git fetch origin
            git checkout implement-custom-notification-for-slack-app
            git pull origin implement-custom-notification-for-slack-app
            
            docker-compose up -d --build
            
            # Fix ownership issue
            docker exec -u root bookstack-demo_app_1 git config --global --add safe.directory /app